/**
 * BBM Gagarin
 * API для электронного дневника
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TestEntity {
    'id': string;
    'type': string;
    'userId': number;
    'isCompleted'?: boolean;
    'result': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number",
            "format": ""
        },
        {
            "name": "isCompleted",
            "baseName": "isCompleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TestEntity.attributeTypeMap;
    }

    public constructor() {
    }
}

