/**
 * BBM Gagarin
 * API для электронного дневника
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ProfileEntity {
  'id'?: string;
  'userId'?: number;
  'groupId'?: string;
  'firstName': string;
  'lastName': string;
  'middleName'?: string;
  'birthday'?: Date | null;
  'acceptTerms': boolean;
  'phone'?: string | null;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
    {
      "name": "id",
      "baseName": "id",
      "type": "string",
      "format": ""
    },
    {
      "name": "userId",
      "baseName": "userId",
      "type": "any",
      "format": ""
    },
    {
      "name": "groupId",
      "baseName": "groupId",
      "type": "any",
      "format": ""
    },
    {
      "name": "firstName",
      "baseName": "firstName",
      "type": "string",
      "format": ""
    },
    {
      "name": "lastName",
      "baseName": "lastName",
      "type": "string",
      "format": ""
    },
    {
      "name": "middleName",
      "baseName": "middleName",
      "type": "string",
      "format": ""
    },
    {
      "name": "birthday",
      "baseName": "birthday",
      "type": "Date",
      "format": "date-time"
    },
    {
      "name": "acceptTerms",
      "baseName": "acceptTerms",
      "type": "boolean",
      "format": ""
    }    ];

  static getAttributeTypeMap() {
    return ProfileEntity.attributeTypeMap;
  }

  public constructor() {
  }
}

